export const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";
export const SET_SORT_BY = "SET_SORT_BY";
export const REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST";
export const FETCH_MOVIES_SUCCESS ="FETCH_MOVIES_SUCCESS";